# Generated by Django 4.0.5 on 2023-02-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_response_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='response',
            name='body',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.question'),
        ),
    ]
